# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hesta CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: pip install hestia_earth.utils
    - run: pip install pandas
    - run: npm test

    - name: Build and Start Container
        run: |
          docker build -t hestia .
          docker run -dp 4000:4000 hestia
    
      - name: Confirm application is running
        run: docker ps

      - name: Install locust
        run: pip3 install locust
        
      
      - name: Run load test
        run: |
        cd test/load
        ls
        locust -f locustfile.py --headless -u 100 -r 5 --run-time "20s" -H "http://localhost:4000"
